version: '3.9'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6370:6379"
    volumes:
      - redis_data:/data
    entrypoint: redis-server --appendonly yes
volumes:
  redis_data:
networks:
  default:
    name: scrape_scheduler_network